### ISSUE TITLE
Unable to clean mizu resources or run mizu again

### ISSUE THREAD

**Issue by dttrian** [up9inc/mizu#1107]
**Describe the bug**
I have run mizu to tap one of my pods and it worked flawlessly.
When I finished with it, I tried to interrupt it with CTRL+C, but I had an error at the end: the mizu namespace removal timed out.
I tried then to remove the mizu namespace by hand `kubectl delete namespace mizu` but it failed either.
I checked and the mizu namespace seems empty.
I then tried to run again mizu but it says:

```
Waiting for Mizu Agent to start...
Mizu is already running in this namespace, change the `mizu-resources-namespace` configuration or run `mizu clean` to remove the currently running Mizu instance
```

Unfortunately `mizu cleanup` is not working either.

**To Reproduce**
1. Run `mizu clean`
2. See:
```
Failed dump logs no mizu pods found in namespace mizu

Removing mizu resources
←[1;31mTimeout while removing Namespace mizu←[0m
```

**Expected behavior**
I would expect to be able to clean up mizu or, at least, be able to run it again.

**Logs**
[mizu_cli.zip](https://github.com/up9inc/mizu/files/8757031/mizu_cli.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional
 - Web Browser: Google Chrome

**Additional context**
The kubernetes cluster is managed via Rancher.

**Comment by gadotroee** [comment]
Hi @dttrian, 

It seems like there is timeout in the namespace deletion. 
I don't see any other failure in the logs (because there is no pods running). 

if you can check if there is any resource left in the namespace (`kubectl get all -n mizu`) and if there is any resource please let me know.

if there is no resource maybe there is another problem in the cluster that preventing deletion of namespace?

**Comment by dttrian** [comment]
Hi @gadotroee,
    yes, the namespace deletion times out (also when I try it manually).
As stated previously the mizu namespace seems empty:
```
C:\> kubectl get all -n mizu
No resources found in mizu namespace.
```

Rancher-side I see that the namespace is "Terminating":
![image](https://user-images.githubusercontent.com/55129227/169982154-3dce0653-d1b2-46a7-a820-4cdcf61b58d2.png)

Is there anything I can do to force mizu to run even if the mizu namespace already exists?

**Comment by dttrian** [comment]
It was not a mizu specific problem: the mizu namespace couldn't be deleted because it was locked by a backup system (kasten k10).
