### ISSUE TITLE
When using ^C to stop Mizu leaves it's damonset and all other resources behind

### ISSUE THREAD

**Issue by NeckBeardPrince** [up9inc/mizu#112]
The pods will start to crash, and you have to go in and manually delete the damonset and all other resources.

**Comment by RamiBerm** [comment]
Can't seem to reproduce this issue on my end, can you provide the steps you made to reproduce this issue?

**Comment by IgorGov** [comment]
@NeckBeardPrince I am closing this issue because of its inactivity, feel free to reopen or open a new one if you still experiencing the issue.
