### ISSUE TITLE
Helm command line is incorrect in https://getmizu.io/docs/installing-mizu/centralized-installation

### ISSUE THREAD

**Issue by ogerardin** [up9inc/mizu#1135]
**Describe the bug**
Section "Install Mizu Pro with Helm Chart" of "Centralized installation" page has:
`helm install mizu up9mizu --repo https:///static.up9.com/mizu/helm --namespace mizu --create-namespace --wait --atomic`

**To Reproduce**
Open https://getmizu.io/docs/installing-mizu/centralized-installation

**Expected behavior**
Should be 
`helm install mizu up9mizu --repo https://static.up9.com/mizu/helm --namespace mizu --create-namespace --wait --atomic` (2 slashes not 3)

**Logs**
n/a

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Additional context**
Couldn't find the source for this in the repo

**Comment by gadotroee** [comment]
Hi @ogerardin,

Thanks for letting us know about this mistake. 
I will handle the fix (the website of mizu is not in this repo so you should not be able to find it)

I will update when it is fixed.

**Comment by gadotroee** [comment]
Updated the docs to contains the correct command
