### ISSUE TITLE
Installing with mizu client does not create elasticsearch pod

### ISSUE THREAD

**Issue by ogerardin** [up9inc/mizu#1136]
**Describe the bug**
When installing using the CLI, only the "mizu-api-server" pod is installed, but it won't start because the "wait-for-elasticsearch-master" container never succeeds as the pod "elasticsearch-master" is not created.

**To Reproduce**
1. Run `mizu install -o | kubectl apply -f -`

**Expected behavior**
"elasticsearch-master" pod is running
"mizu-api-server" pod is running

**Logs**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Web Browser: n/a

**Additional context**
Installing with Helm creates both pods mizu-api-server and elasticsearch-master.

**Comment by gadotroee** [comment]
Hi @ogerardin , 

We will take a look and fix it soon.
I hope the installation with helm worked for you after all and you can use the application.
Thanks

**Comment by ogerardin** [comment]
> The elastic pod was created on different namespace

Correct.. I found and deleted the unwanted one

> this [hotfix](https://github.com/up9inc/mizu/pull/1142) should fix this. The installation command changed, you will be able to see the updated command in [33.1 release](https://github.com/up9inc/mizu/releases/tag/33.1), the new command should like: `./mizu install -o | kubectl apply -n mizu -f -`

That seems to have fixed it!
Thanks
