### ISSUE TITLE
Don't get traffic from my pods

### ISSUE THREAD

**Issue by Baronzimo** [up9inc/mizu#1222]
One month ago I use Mizu and see all the  traffic but I tried now, in  another machine, and don't have any of the traffic in Web UI, 

![ok](https://user-images.githubusercontent.com/79194657/198139256-62489a3c-a6c3-441b-9d46-9031f9043cce.png)
![345](https://user-images.githubusercontent.com/79194657/198139290-e139f37b-d5de-499f-9289-3c85fc0db827.png)

**Comment by alongir** [comment]
Thanks, I asked one of the devs to look in to it

**Comment by mertyildiran** [comment]
@Baronzimo you're tapping the pods in the `kube-system` namespace:

> `kube-system` The namespace for objects created by the Kubernetes system ([source](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#viewing-namespaces))

I think the pods in `kube-system` is not generating any traffic for the [application layer protocols that are supported by Mizu](https://github.com/up9inc/mizu/wiki/Introduction-to-Mizu#tapper).

Did you actually intend to tap another namespace? If so, the command below is the correct usage:

> mizu tap -n example-namespace

**Comment by Baronzimo** [comment]
> @Baronzimo you're tapping the pods in the `kube-system` namespace:
> 
> 
> 
> > `kube-system` The namespace for objects created by the Kubernetes system ([source](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#viewing-namespaces))
> 
> 
> 
> I think the pods in `kube-system` is not generating any traffic for the [application layer protocols that are supported by Mizu](https://github.com/up9inc/mizu/wiki/Introduction-to-Mizu#tapper).
> 
> 
> 
> Did you actually intend to tap another namespace? If so, the command below is the correct usage:
> 
> 
> 
> ```
> 
> mizu tap -n example-namespace
> 
> ```
> 
> 
> 
> If you used `mizu tap -A` but Mizu only tapped `kube-system` namespace then most probably; it's either there are no other namespaces in your cluster or Mizu is missing one of [these permissions](https://getmizu.io/docs/installing-mizu/mizu-permissions).

thanks for the reply

i Reinstall in many times, this time its Works, the problem is maybe with Kubernetes not Mizu, i install micro8ks for ubuntu this time and take Kubectl also, and create config file from microk8s and its Works fine this time.

**Comment by mertyildiran** [comment]
Closing the issue since it's marked as invalid.
