### ISSUE TITLE
getting this error in AWS EKS

### ISSUE THREAD

**Issue by neeltom92** [up9inc/mizu#130]
I use aws EKS  , set the kubeconfig using the below command:
aws eks update-kubeconfig --name <cluster_value> --kubeconfig <path/value> --region <value>

then set a alias to the kubeconfig.

While running the mizu command getting the error below:

![image](https://user-images.githubusercontent.com/26869835/126518343-c7512e32-65cf-4fae-abbb-a82d7a66797c.png)

**Comment by IgorGov** [comment]
Hi Neel Thomas, 
Thanks for reaching out.
Can you try setting explicitly the location of your kube config path by adding the '--kube-config' param:
`mizu tap prod-capi-deployment-9f8b6c4f9-8rtwq -A --kube-config=<full path to your kube config (e.g /Users/igor/.kube/config)>`

**Comment by neeltom92** [comment]
thanks its resolved

**Comment by IgorGov** [comment]
Glad to hear, closing this issue
