### ISSUE TITLE
Service Unavailable (cont)

### ISSUE THREAD

**Issue by fabfianda** [up9inc/mizu#242]
Hi guys,
re-opening the ticket as latest version is not working on my clusters reporting again:

message | "error trying to reach service: dial tcp 10.2.63.158:8899: i/o timeout"

This time though I'm attaching the logs dump as [requested.](url)
[mizu_logs_2021_08_20__11_21_32.zip](https://github.com/up9inc/mizu/files/7020520/mizu_logs_2021_08_20__11_21_32.zip)

**Comment by IgorGov** [comment]
Hi @fabfianda, 
Thanks for the additional data, we will take a look at it.
Attaching here the link to your previous ticket:
https://github.com/up9inc/mizu/issues/153

**Comment by gadotroee** [comment]
Hi @fabfianda 
We recently released new version that might solve your problem (it had some changes in the communication infrastructure and more information in case of failure)

I'm closing this issue and and you and if you are still see this issue you are more than welcome to re-open maybe with more details.

Thanks.
