### ISSUE TITLE
Error updating tappers: 415: Unsupported Media Type

### ISSUE THREAD

**Issue by yili1992** [up9inc/mizu#361]
![截屏2021-10-15 下午4 31 22](https://user-images.githubusercontent.com/3176589/137457497-ca42f906-210c-4788-932b-4dca61119625.png)

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

[mizu_logs_2021_10_19__13_53_54.zip](https://github.com/up9inc/mizu/files/7370579/mizu_logs_2021_10_19__13_53_54.zip)

**Comment by mertyildiran** [comment]
Seems like [Kubernetes API Server](https://kubernetes.io/docs/concepts/overview/kubernetes-api/) returning `415`.

The error is sourced from [this function](https://github.com/up9inc/mizu/blob/256006ca3e710b6f0e229963bb6e0cd6ebc05cb2/cli/kubernetes/provider.go#L481-L599) but I couldn't actually reproduce it. @nimrod-up9 do you have any idea?

The error message probably comes from [this line in Kubernetes](https://github.com/kubernetes/kubernetes/blob/655c04d9f530e5ebc2ec6f5feef76716c8a9db22/vendor/github.com/emicklei/go-restful/jsr311.go#L118).

**Comment by nimrod-up9** [comment]
@yili1992 Could you also provide the output of `kubectl version` command?
