### ISSUE TITLE
error: error in k8s watch

### ISSUE THREAD

**Issue by fferraro87** [up9inc/mizu#558]
Hi,
i've start mizu on my machine but i've that error :
```
Waiting for Mizu Agent to start...
Watching API server events loop, error: error in k8s watch: the server could not find the requested resource (get events.events.k8s.io)
Mizu is available at http://localhost:8899
Watching tapper events loop, error: error in k8s watch: the server could not find the requested resource (get events.events.k8s.io)
```
do you know how can i fix?

**Comment by IgorGov** [comment]
In mizu cli, it executes k8s watch events command, the error says that it can't find resource `events.events.k8s.io`, which points to client/server version compatibility issue. Can you make sure that your client and server versions are compatible with:
`kubectl version`

BTW, except the error were you able to see the traffic?

**Comment by fferraro87** [comment]
hi thanks, 
i've v1.18.10 kubernetes cluster and i've kubectl-1.23 on my client installed.
Nope from mizu dashboard, i cannot see anything, i've this https://imgur.com/uBsF8To 
i cannot press also on "play"

**Comment by IgorGov** [comment]
can you try downgrade your client to same version as server (v1.18.10)?

**Comment by fferraro87** [comment]
i've downgraded to v1.18.10 but i've same problem, and as before on dashboard i can't do anything

**Comment by fferraro87** [comment]
but it's also strange that error because i can see events from kubectl and i can use -w option without any problems

**Comment by IgorGov** [comment]
Can you please add logs. You can run mizu with `--set dump-logs=true` flag. The full mizu command will look something like:
`./mizu tap --set dump-logs=true`

**Comment by fferraro87** [comment]
i'll send you log file on your email it's ok?

**Comment by IgorGov** [comment]
Sure, igor@up9.com

**Comment by IgorGov** [comment]
@fferraro87 tried to access the UI not from same machine where Mizu CLI was running. That why the communication didn't work between UI component and Mizu API server.
The solution in his case was using the following flag: 
`tap.proxy-host=0.0.0.0`
Closing the issue
