### ISSUE TITLE
config:  image-pull-policy: IfNotPresent 

### ISSUE THREAD

**Issue by VanLiuZhi** [up9inc/mizu#564]
I modified the configuration file, but it didn't take effect

`Mizu API Server status: Failed - Failed to pull image "gcr.io/up9-docker-hub/mizu/develop:0.21.8": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/: unexpected EOF
`

I can't access gcr.io，so I downloaded the image locally

**Comment by IgorGov** [comment]
you can use `--set agent-image=<your image location>` flag, the full command will look similar to:
`./mizu tap --set agent-image=<your image location>`
