### ISSUE TITLE
Mizu API Server status: Failed - Error: ErrImagePull

### ISSUE THREAD

**Issue by yangvipguang** [up9inc/mizu#568]
![image](https://user-images.githubusercontent.com/11416887/147636921-dadfcb72-974a-4a7b-b3db-a7b51725c735.png)

I do't know how to fix it? whereis the image?

**Comment by nimrod-up9** [comment]
Hi @yangvipguang, thank you for submitting an issue.

The image is publicly accessible on gcr (google container registry).
For the latest stable release, `v0.21.0`, the image should be `gcr.io/up9-docker-hub/mizu/main:0.21.0`.
Does your cluster have access to public images and permissions to pull them?

**Comment by yangvipguang** [comment]
@nimrod-up9  I know what's wrong. I am in china , so we can't access  google normally . can i change the repo with config or subcommand ?

**Comment by IgorGov** [comment]
you can use --set agent-image=<your image location> flag, the full command will look similar to:
./mizu tap --set agent-image=<your image location>.

**Comment by yangvipguang** [comment]
@IgorGov  thx,it works
