### ISSUE TITLE
sorry, endpoint is not found

### ISSUE THREAD

**Issue by 4ss3g4f** [up9inc/mizu#579]
![image](https://user-images.githubusercontent.com/22811935/147868961-30bc243c-1868-4a16-aa51-5097d93aec38.png)

![image](https://user-images.githubusercontent.com/22811935/147868972-084ac7ef-9f31-4a12-ad83-3bcf711a9d03.png)

Kubernetes version: v1.23.0

![image](https://user-images.githubusercontent.com/22811935/147868996-b7150c10-5f96-4905-876f-2eefe87cca27.png)

Can't open mizu url http://localhost:8899/mizu

**Comment by IgorGov** [comment]
Hi @4ss3g4f , thanks for reaching out, the correct URL is http://localhost:8899, the readme should be fixed now.
