### ISSUE TITLE
Documentation broken URL for sensitiveDataFiltering

### ISSUE THREAD

**Issue by fedemengo** [up9inc/mizu#601]
**Describe the bug**
I just came across mizu, I was reading the documentation over at https://getmizu.io/. In the Security section, the url for the redacted keyworkds is broken. 

**To Reproduce**
1. Visit https://getmizu.io/#:~:text=https%3A//github.com/up9inc/mizu/blob/develop/agent/pkg/sensitiveDataFiltering (chrome link to the url)
2. Click on 'sensitiveDataFiltering`

**Expected behavior**
I would expect the link to work

**Comment by mertyildiran** [comment]
@fedemengo I'm sorry, we moved the file to [here](https://github.com/up9inc/mizu/blob/main/tap/extensions/http/sensitive_data_cleaner.go) but forgot to update the link on the website. The website will soon be updated.

**Comment by imceZZ** [comment]
@fedemengo @mertyildiran link is updated.
