### ISSUE TITLE
Mizu API server was not ready in time

### ISSUE THREAD

**Issue by andyoulovexy** [up9inc/mizu#613]
[root@k8s-master-xxx mizu]# ./mizu tap
Mizu will store up to 200MB of traffic, old traffic will be cleared once the limit is reached.
Tapping pods in namespaces "default"
+kali-roll-df47956b5-5mdtp
+my-cert-manager-cainjector-5955cd77f8-j5g5x
+my-cert-manager-ff65454bf-q547x
+my-cert-manager-webhook-5ff8499f89-jmrrj
+vault-7594bfbc57-vc4fx
Waiting for Mizu Agent to start...
Mizu API server was not ready in time

Removing mizu resources

**Comment by RoyUP9** [comment]
Hey @andyoulovexy,
Thanks for reaching out.

I want to make sure it is not an issue in the proxy, so i can suggest you do the following:

1. You can Run the command `API_SERVER_RETRIES=100 ./mizu tap --set dump-logs=true` (We’ve added the option to extend the retries count in order to give more time to debug the problem)
2. Try to reach the following url: `http://localhost:8899/api/v1/namespaces/mizu/services/mizu-api-server/proxy/`, do you see Mizu UI?
3. Can you try to run `kubectl proxy`, do you see any errors? Can you navigate now to the proxy served url and get response from k8s? - you should be able to see the "version" endpoint, in my laptop it is in port 8001 by default so I can go to `http://127.0.0.1:8001/version` and see k8s version details
4. Could you please provide us with the zip containing the logs from the run?

Thanks!

**Comment by andyoulovexy** [comment]
> Hey @andyoulovexy, Thanks for reaching out.
> 
> I want to make sure it is not an issue in the proxy, so i can suggest you do the following:
> 
> 1. You can Run the command `API_SERVER_RETRIES=100 ./mizu tap --set dump-logs=true` (We’ve added the option to extend the retries count in order to give more time to debug the problem)
> 2. Try to reach the following url: `http://localhost:8899/api/v1/namespaces/mizu/services/mizu-api-server/proxy/`, do you see Mizu UI?
> 3. Can you try to run `kubectl proxy`, do you see any errors? Can you navigate now to the proxy served url and get response from k8s? - you should be able to see the "version" endpoint, in my laptop it is in port 8001 by default so I can go to `http://127.0.0.1:8001/version` and see k8s version details
> 4. Could you please provide us with the zip containing the logs from the run?
> 
> Thanks!
[mizu_logs_2022_01_10__15_41_04.zip](https://github.com/up9inc/mizu/files/7837364/mizu_logs_2022_01_10__15_41_04.zip)

This is zip,Thanks

**Comment by RoyUP9** [comment]
Hey, @andyoulovexy 
Thanks for your quick reply.

Looks like you're having trouble pulling mizu's image.

The image is publicly accessible on gcr (google container registry).
For the latest stable release, v0.21.0, the image should be gcr.io/up9-docker-hub/mizu/main:0.21.0.
Does your cluster have access to public images and permissions to pull them?

If not, you can download the image and run mizu with --set agent-image=<your image location> flag, the full command will look similar to:
./mizu tap --set agent-image=<your image location>.

Thanks!

**Comment by andyoulovexy** [comment]
> 

I had this images,but the same error to me
![image](https://user-images.githubusercontent.com/38940994/148735808-4d336f75-af28-432f-ba24-cfbcd355e411.png)

**Comment by andyoulovexy** [comment]
> Hey, @andyoulovexy Thanks for your quick reply.
> 
> Looks like you're having trouble pulling mizu's image.
> 
> The image is publicly accessible on gcr (google container registry). For the latest stable release, `v0.21.0`, the image should be `gcr.io/up9-docker-hub/mizu/main:0.21.0`. Does your cluster have access to public images and permissions to pull them?
> 
> If not, you can download the image and run mizu with `--set agent-image=<your image location>` flag, the full command will look similar to: `./mizu tap --set agent-image=<your image location>`.
> 
> Thanks!
I had this images,but the same error to me
![image](https://user-images.githubusercontent.com/38940994/148736018-3c1b0333-3ed8-456d-b603-976eed621a36.png)

**Comment by haiut** [comment]
@andyoulovexy could you please try simply pulling the image to the local computer, so we rule out any network / image download issues ?  If you could run the following:
`docker pull gcr.io/up9-docker-hub/mizu/main:0.21.0`

Expected output would be something like
```
$ docker pull gcr.io/up9-docker-hub/mizu/main:0.21.0
0.21.0: Pulling from up9-docker-hub/mizu/main
97518928ae5f: Pull complete
7aab60cfb68a: Pull complete
ecf028e61a18: Pull complete
098fcca86bda: Pull complete
af61399ff2b0: Pull complete
cb60a6f698b7: Pull complete
76eaf4a2f41a: Pull complete
fbf8ce92c82a: Pull complete
Digest: sha256:3420ab5bdf5daa8af7ae922178445a6d0ba79579c511194649b1d116e6142e12
Status: Downloaded newer image for gcr.io/up9-docker-hub/mizu/main:0.21.0
gcr.io/up9-docker-hub/mizu/main:0.21.0
$
```

**Comment by andyoulovexy** [comment]
> @andyoulovexy could you please try simply pulling the image to the local computer, so we rule out any network / image download issues ? If you could run the following: `docker pull gcr.io/up9-docker-hub/mizu/main:0.21.0`
> 
> Expected output would be something like
> 
> ```
> $ docker pull gcr.io/up9-docker-hub/mizu/main:0.21.0
> 0.21.0: Pulling from up9-docker-hub/mizu/main
> 97518928ae5f: Pull complete
> 7aab60cfb68a: Pull complete
> ecf028e61a18: Pull complete
> 098fcca86bda: Pull complete
> af61399ff2b0: Pull complete
> cb60a6f698b7: Pull complete
> 76eaf4a2f41a: Pull complete
> fbf8ce92c82a: Pull complete
> Digest: sha256:3420ab5bdf5daa8af7ae922178445a6d0ba79579c511194649b1d116e6142e12
> Status: Downloaded newer image for gcr.io/up9-docker-hub/mizu/main:0.21.0
> gcr.io/up9-docker-hub/mizu/main:0.21.0
> $
> ```

1、I had pulld images through hongkong vm machine
2、I load image to local machine，docker load < mizu.tar
3、I run it： ./mizu tap --set agent-image=gcr.io/up9-docker-hub/mizu/main:0.21.0，get error:
./mizu tap --set agent-image=gcr.io/up9-docker-hub/mizu/main:0.21.0
Mizu will store up to 200MB of traffic, old traffic will be cleared once the limit is reached.
Tapping pods in namespaces "default"
+kali-roll-df47956b5-5mdtp
+my-cert-manager-cainjector-5955cd77f8-j5g5x
+my-cert-manager-ff65454bf-q547x
+my-cert-manager-webhook-5ff8499f89-jmrrj
+vault-7594bfbc57-vc4fx
Waiting for Mizu Agent to start...
Mizu API server was not ready in time

Removing mizu resources

**Comment by andyoulovexy** [comment]
> @andyoulovexy could you please try simply pulling the image to the local computer, so we rule out any network / image download issues ? If you could run the following: `docker pull gcr.io/up9-docker-hub/mizu/main:0.21.0`
> 
> Expected output would be something like
> 
> ```
> $ docker pull gcr.io/up9-docker-hub/mizu/main:0.21.0
> 0.21.0: Pulling from up9-docker-hub/mizu/main
> 97518928ae5f: Pull complete
> 7aab60cfb68a: Pull complete
> ecf028e61a18: Pull complete
> 098fcca86bda: Pull complete
> af61399ff2b0: Pull complete
> cb60a6f698b7: Pull complete
> 76eaf4a2f41a: Pull complete
> fbf8ce92c82a: Pull complete
> Digest: sha256:3420ab5bdf5daa8af7ae922178445a6d0ba79579c511194649b1d116e6142e12
> Status: Downloaded newer image for gcr.io/up9-docker-hub/mizu/main:0.21.0
> gcr.io/up9-docker-hub/mizu/main:0.21.0
> $
> ```

I had pulld images through hongkong vm machine

**Comment by haiut** [comment]
OK, I see. The problem is that your k8s cluster can't pull the images directly from our container registry at Google Cloud `gcr.io/up9-docker-hub/mizu/main:0.21.0`. You managed to download and import it the image into docker on the local machine,  but it's still not accessible to the k8s.  If you're running a **minikube** on your local computer and would like to use images already downloaded to your computer (visible with `docker images`) - please try the steps described in this post - https://stackoverflow.com/a/42564211

Anyway, we understand the problem now - let us look into this and see if we can offer something else.

**Comment by andyoulovexy** [comment]
> OK, I see. The problem is that your k8s cluster can't pull the images directly from our container registry at Google Cloud `gcr.io/up9-docker-hub/mizu/main:0.21.0`. You managed to download and import it the image into docker on the local machine, but it's still not accessible to the k8s. If you're running a **minikube** on your local computer and would like to use images already downloaded to your computer (visible with `docker images`) - please try the steps described in this post - https://stackoverflow.com/a/42564211
> 
> Anyway, we understand the problem now - let us look into this and see if we can offer something else.

It had imagepullpolicy?if local machine already had images,i need pull images?

**Comment by RoyUP9** [comment]
The problem is that you pulled the image into your local machine, but it's still not accessible to the k8s cluster that you're using to run mizu.

Can you please confirm you are using minikube? if so, we will try to offer you a solution for that.

**Comment by andyoulovexy** [comment]
> The problem is that you pulled the image into your local machine, but it's still not accessible to the k8s cluster that you're using to run mizu.
> 
> Can you please confirm you are using minikube? if so, we will try to offer you a solution for that.

[root@k8s-workerxxx ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by RoyUP9** [comment]
In order for it to work, you will need to save the image in a registry which the cluster can access,
and change --set `agent-image=<your image location>` flag to this location.

Can you describe your k8s setup? it there a container registry you can load mizu's image to?

**Comment by andyoulovexy** [comment]
> In order for it to work, you will need to save the image in a registry which the cluster can access, and change `--set agent-image=<your image location>` flag to this location.
> 
> Can you describe your k8s setup? it there a container registry you can load mizu's image to?

I Known,I will push this image to my harbor registry,thanks

**Comment by andyoulovexy** [comment]
> OK, I see. The problem is that your k8s cluster can't pull the images directly from our container registry at Google Cloud `gcr.io/up9-docker-hub/mizu/main:0.21.0`. You managed to download and import it the image into docker on the local machine, but it's still not accessible to the k8s. If you're running a **minikube** on your local computer and would like to use images already downloaded to your computer (visible with `docker images`) - please try the steps described in this post - https://stackoverflow.com/a/42564211
> 
> Anyway, we understand the problem now - let us look into this and see if we can offer something else.

Thanks. I need push this image to my private registry,then run it.
