### ISSUE TITLE
Watching API server events loop, error: error in k8s watch: the server could not find the requested resource (get events.events.k8s.io)

### ISSUE THREAD

**Issue by lkgGitHub** [up9inc/mizu#615]
**Describe the bug**
./mizu tap
Mizu will store up to 200MB of traffic, old traffic will be cleared once the limit is reached.
Tapping pods in namespaces "default"
Waiting for Mizu Agent to start...
**Watching API server events loop, error: error in k8s watch: the server could not find the requested resource (get events.events.k8s.io)**
Mizu API server was not ready in time

**To Reproduce**
1. Run `mizu tap`

**Desktop (please complete the following information):**
 - OS: ubuntu18
 - kubernetes: 1.16.3

**Comment by RoyUP9** [comment]
Hey @lkgGitHub 
Thanks for reaching out.

The logs from this run could help identify the problem.

Could you please run mizu using the --set dump-logs=true flag. The full command should look similar to:
./mizu tap --set dump-logs=true

And provide us with the zip containing the logs from the run.

Thanks!

**Comment by IgorGov** [comment]
This issue was fixed. 
Can you try the latest unstable version?

**Comment by ramnes** [comment]
Had the same error, and I can confirm it doesn't happen anymore with 0.21.42.

**Comment by IgorGov** [comment]
@ramnes glad to hear that it works for you, we planing to release a stable version next Sunday.
The error should be in the logs file only as warning, you should not see it in the CLI, but all functionality should work as expected.
If you feel that the it resolved for you you can close this issue

**Comment by gadotroee** [comment]
Hi @lkgGitHub, 

We released version 0.22 today (https://github.com/up9inc/mizu/pull/651).
It include many changes including the fix for your issue, Can you check if the issue resolved?
