### ISSUE TITLE
Minikube - CrashloppBackOff

### ISSUE THREAD

**Issue by BK-STAR77** [up9inc/mizu#634]
**Describe the bug**
mizu-tapper "CrashLoopBackOff"

**Logs**
Upload logs:
[logs-minikube](https://drive.google.com/file/d/1Im0ANrRdU08hexzPI89O1FOrz3SRqLr2/view?usp=sharing)

**Desktop (please complete the following information):**
 - OS: [ macOS - Apple Silicon]
 - Web Browser: [Google Chrome]

**Comment by gadotroee** [comment]
Hi @BK-STAR77 , 

We did saw this issue with apple M1 based server and we are working on fix for this, I will try to update soon about estimation or other solution to make it work for you.

Thanks

**Comment by BK-STAR77** [comment]
> Hi @BK-STAR77 ,
> 
> We did saw this issue with apple M1 based nodes (arm) (which are created when you use minikube on new apple laptop) and we are working on fix for this, I will try to update soon about estimation or other solution to make it work for you.
> 
> Thanks

Thank you

**Comment by gadotroee** [comment]
Hi @BK-STAR77,
we will publish M1 compatible images early next week, and work on creating it automatically for any new version.

Anyway I will update here when there is something that you can use.

**Comment by BK-STAR77** [comment]
@gadotroee Thank you

**Comment by gadotroee** [comment]
Hi @BK-STAR77,

sorry for the delay but we have just released a pre release version that has the support of "arm".

you can try and use: https://github.com/up9inc/mizu/releases/tag/0.22.38, and let me know if it works for you 0 I will try to get estimation for a stable version that contain this functionality

**Comment by BK-STAR77** [comment]
Just installed and it work !! Tested on a Mac Mini M1. MaOS Big Sur 

Thank You

**Comment by gadotroee** [comment]
I see that we didn't update here but we now have a released (stable) version with this support of M1.
I'm closing this issue.
