### ISSUE TITLE
Couldn't connect to API server, for more info check logs

### ISSUE THREAD

**Issue by lalitkr90** [up9inc/mizu#642]
I am not able to launch mizu as whenever I do so, the **mizu-api-server** goes into crashloopbackoff state with the below error.
It gives, Failed to get token, Get https://trcc.up9.app/anynonymous/token.

![image](https://user-images.githubusercontent.com/47416276/149512573-8eb2088c-a0a7-4410-b248-e8fbdee03102.png)

The K8s version in my environment is 1.20.6
Moreover, when I ran mizu on my mac terminal (k8s version: 1.21.2), mizu-api-server pod yaml that got generated as a result was different from what  got while running it in private environment. And on mac terminal its running fine.

In the earlier case it is using the projected volume to obtain the token, but in latter it is directly giving the reference to the service account token using which it is trying to reach some external URL it seems.
MAC mizu api pod for token reference:
![image](https://user-images.githubusercontent.com/47416276/149514196-4e3e7366-2681-4598-a138-615ba3fa5d62.png)

Private env api pod for token reference:
![image](https://user-images.githubusercontent.com/47416276/149514387-23d365ad-ad3f-470b-9e63-fe8c2ce35b7f.png)

As a workaround to fix the mizu-api-server pod, I referenced the token using the projected volume and it stabilized the api server and I was able to access MIZU GUI as well. 
But due to this, I had to terminate the earlier instance of mizu api server and launch a new one due to which on mizu GUI I wasn't able to see any tapped pods.

My doubt is that it should be generating the similar api server pod yaml as it was giving on mac terminal, it shouldn't try to reach external URL for fetching the token.
And is there any functionality using which I can keep running on the mizu api pod and can tap the pods later.

I have attached the mizu_cli.log as reference.
Let me know in case any other details are needed.

Below is the config file.
![image](https://user-images.githubusercontent.com/47416276/149518484-9d15932c-bbd5-40fc-a4ae-acf9dfe305aa.png)

[mizu_cli.log](https://github.com/up9inc/mizu/files/7870436/mizu_cli.log)
[mizu_events.log](https://github.com/up9inc/mizu/files/7870438/mizu_events.log)

**Comment by gadotroee** [comment]
Hi @lalitkr90,

Thanks for reaching and sharing your results, from what I can see you are using the option of analysis. 

This is what causing the request to get the token and upload the data for more processing that can give you more information. (This is the request you see to trcc.up9.app).

I can see from your config that it is set to "true" so just wanted to know if you change it 


Also, I'm not exactly sure what do you mean when you run it on your Mac (and what is the second option)

Hope my question make sense,
You can also join our slack and maybe it will be easier to communicate there (this is the slack invite link - https://join.slack.com/t/up9/shared_invite/zt-tfjnduli-QzlR8VV4Z1w3YnPIAJfhlQ

**Comment by IgorGov** [comment]
According to your configuration you set tap.analsys=True. This option enables advanced analysis of collected traffic in the UP9 cloud platform. 
Mizu is tries to send the traffic to [up9.app](up9.app), but it seems it could not reach it from you k8s cluster. This is the reason for the panic.
As a workaround you can disable this option and it should work for you. If you would like to use this feature you should enable connectivity from mizu pod to [up9.app](up9.app).

Anyway I think it better not to panic in this case, so I pushed this change:
https://github.com/up9inc/mizu/pull/648

**Comment by lalitkr90** [comment]
@IgorGov I was able to launch mizu-api-server with the settings that you suggested and UI was also coming up but still it is not tapping any pods and shows that it is waiting for the agent to start.
In the end it still gives, couldn't connect to API server.

MIZU GUI showing 0 tapped pods.
![image](https://user-images.githubusercontent.com/47416276/149757340-9a2f0044-057e-435e-95fa-e710bef45bc3.png)

MIZU start logs:
![image](https://user-images.githubusercontent.com/47416276/149757428-25bcf57a-7c83-4f51-a2b5-2057a25e69e6.png)

MIZU api server logs:
![image](https://user-images.githubusercontent.com/47416276/149757609-994e52ca-25c0-457c-b414-157a02fe2bfe.png)

MIZU cli logs:
[mizu_logs_2022_01_17__05_57_16.zip](https://github.com/up9inc/mizu/files/7881308/mizu_logs_2022_01_17__05_57_16.zip)

**Comment by IgorGov** [comment]
It seems like the CLI can't establish proxy connection (with kubectl client) to Mizu Agent in k8s cluster. But I see that you somehow manage to connect to Mizu Agent and see the GUI. We are currently working to fix these connectivity issues.
Meanwhile I can suggest to use our latest release [0.22.0](https://github.com/up9inc/mizu/releases/tag/0.22.0), and run `./mizu install` - it should install all k8s components, then you can connect to Mizu service with your preferred method (port forward, node port, proxy), or expose it with load balancer for instance.
You can always clean all mizu resources with `./mizu clean`.
Notice that it will request setup up password at your first login.

**Comment by lalitkr90** [comment]
@IgorGov In the latest version, is there any option to specify the images for kratos and basenine with your private registry because mizu-api-server was unable to pull these images.
I manually pushed those images and edited the deployment for mizu-api-server and the pod was able to pull images but kratos is giving failed readiness probe. 
Both the kratos and mizu-api-server container restarted 1 time each.
Pod state is still 2/3 running as kratos is not ready yet.
Below are the logs for the kratos and mizu-api-server container when they got restarted.

Kratos logs:
![image](https://user-images.githubusercontent.com/47416276/149801301-fba644c1-f365-45cf-af07-070f4dde8340.png)

Mizu-api-server logs:
![image](https://user-images.githubusercontent.com/47416276/149801436-6738e497-eaad-4201-b68a-f5afef1d5897.png)

Pod state:
![image](https://user-images.githubusercontent.com/47416276/149801598-a2c1b04d-8449-40de-88c8-1b1f25888093.png)

**Comment by gadotroee** [comment]
Hi, @lalitkr90, 

We are aware of problems in private clusters, we are working on a fix for it, part of this fix will allow specify the image for the database and the kratos images.

I will update here when it is ready (might be in a day or two).

**Comment by gadotroee** [comment]
Hi @lalitkr90 , in the latest pre-release version we have option to specify the "basenine" image. we will add option to specify kratos image location soon too.

Also we have merged https://github.com/up9inc/mizu/pull/662 that uses port-forward if proxy is not available, it might with some issues you saw.

I will update when we are changing the kratos to be configurable
