### ISSUE TITLE
An error is reported during deployment

### ISSUE THREAD

**Issue by aishad-weiying** [up9inc/mizu#680]
When accessing the web interface, an error panic is reported. There is no operation, but the mouse clicks

`[2022-01-23T14:12:27.728+0000] INFO  ▶ Websocket event - Browser socket connected, socket ID: 10 ▶ [1 socket_server_handlers.go:35 WebSocketConnect]
2022/01/23 14:12:27 Reached EOF on server connection.
[2022-01-23T14:12:32.211+0000] INFO  ▶ Websocket event - Browser socket disconnected, socket ID:  10 ▶ [1 socket_server_handlers.go:47 WebSocketDisconnect]
2022/01/23 14:12:32 Reached EOF on server connection.
2022/01/23 14:12:32 http: response.Write on hijacked connection from github.com/gin-gonic/gin.(*responseWriter).Write (response_writer.go:78)

2022/01/23 14:12:32 [Recovery] 2022/01/23 - 14:12:32 panic recovered:
http: connection has been hijacked
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/render/json.go:56 (0x21165a6)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:927 (0x211c248)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:970 (0x213527e)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:199 (0x213521e)
/app/agent-build/pkg/middlewares/requiresAuth.go:27 (0x21351ac)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x2134b82)
/app/agent-build/pkg/middlewares/cors.go:17 (0x2134b69)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x216fe5b)
/app/agent-build/main.go:283 (0x216fe42)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x212e179)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/recovery.go:99 (0x212e160)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x212d253)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/logger.go:241 (0x212d212)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x2122eaf)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:555 (0x2122e95)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:511 (0x212294a)
/usr/local/go/src/net/http/server.go:2868 (0xf3b222)
/usr/local/go/src/net/http/server.go:1933 (0xf3664c)
/usr/local/go/src/runtime/asm_amd64.s:1371 (0xc6e700)`

**Comment by aishad-weiying** [comment]
mizu version: 0.22.22
kubernetes:v1.18.2
system:Ubuntu 20.04.2

**Comment by RamiBerm** [comment]
@aishad-weiying thanks for reaching out.
Can you please run again with `--set dump-logs=true`, after the execution ends you should find the logs in `~/.mizu/mizu_logs_**.zip`, can you please attach them here?
The full command will look like:

`mizu tap --set dump-logs=true`

**Comment by aishad-weiying** [comment]
i'm run ./mizu install and mizu tap -A,If only ./mizu tap -A ,Then the program is normal,Is there a problem with the use of the install option

**Comment by RamiBerm** [comment]
I'm curious to know more about what went wrong when you ran `mizu install`
Have you tried configuring all namespaces in the tapping settings? (like in this screenshot)

**Comment by RamiBerm** [comment]
I'm curious to know what went wrong when you ran `mizu install`, have you tried configuring all namespaces in the tapping settings? (see screenshot)
![image](https://user-images.githubusercontent.com/54766858/151139283-a3159628-d5fc-4b7f-998a-304581925070.png)

If that doesn't work, can you run `mizu logs` after running `mizu install` and send the resulting log zip file here? this will help us understand what doesnt work

Thanks
