### ISSUE TITLE
Kubernetes fails to pull the image

### ISSUE THREAD

**Issue by fulcrum29** [up9inc/mizu#693]
**Describe the bug**
When trying to deploy mizu to kuberenetes cluster, kuberenetes fails to pull the image from ecr with error
`container "mizu-api-server" in pod "mizu-api-server-7b9df6dcb9-j5ljp" is waiting to start: trying and failing to pull image`
I tried to pull the image myself
`docker pull 709825985650.dkr.ecr.us-east-1.amazonaws.com/up9/mizufree:0.21.29
Error response from daemon: Head "https://709825985650.dkr.ecr.us-east-1.amazonaws.com/v2/up9/mizufree/manifests/0.21.29": no basic auth credentials`

**To Reproduce**
1. Deploy mizu using helm chart from https://github.com/up9inc/mizu/tree/main/deploy/kubernetes/helm-chart

Links to images
` mizuAgent:
    image:
      repository: "709825985650.dkr.ecr.us-east-1.amazonaws.com/up9/mizufree"
      tag: "0.21.29"
  tapper:
    image:
      repository: "709825985650.dkr.ecr.us-east-1.amazonaws.com/up9/mizufree"
      tag: "0.21.29"`

**Comment by IgorGov** [comment]
Hi @fulcrum29, thanks for reaching out.
Deploying Mizu with helm chart is not officially supported yet (work in progress).
The easy way to deploy mizu and see the traffic is just running CLI command: `./mizu tap`, the helm option is for deploying long running mizu (deployment) with user management and other advanced features.

If you still would like to use helm, attaching a PR which changes the helm to latest publicly accessible release.

**Comment by fulcrum29** [comment]
Thanks, the PR fixes my problem!
