### ISSUE TITLE
Attributing communication to wrong src

### ISSUE THREAD

**Issue by perezjasonr** [up9inc/mizu#779]
**Describe the bug**

I believe mizu might be labeling traffic from erroneous source, for example in my tap of kube-system overwhelming amounts of traffic say:

`src.name == "kube-prometheus-stack-prometheus-node-exporter.monitoring"` (for the record dest is unresolved)

the src ip being ip of the node itself (and not a pod ip), destination ip being just some pod, which is not the node exporter in monitoring ns, it was a kibana pod in a different ns. I assumed this is a healthcheck from kubelet, to kibana pod. why does it keep saying src is node exporter for many like these? I'm specifically running my tap on kube-system, even if the source truly is node-exporter i have 2 questions:

- why is it picking those up? Im not tapping monitoring ns where they (node-exporter) are residing
- why are they **_all_** being attributed to node exporter? I'm not seeing any non-node exporter health checks, arent they being done constantly by kubelet? (meaning isn't it attributing at least some of these checks to some service in monitoring wrongfully?) even if these are accurate id expect to see heath checks from other sources.

**To Reproduce**

I ran mizu tap for a given ns, in my case, kube-system
this was after installing kube-prometheus-stack, which provides node exporter but i think this is a red herring.

**Expected behavior**
src would be attributed to proper source, matching the ip.

**Logs**
Upload logs:

let me know if you want the logs but it appears mizu is working fine from this perspective and probably wont report anything out of the ordinary, i dont think logs will show what im talking about

**Screenshots**
heres an example screen shot

![image](https://user-images.githubusercontent.com/42380628/153045036-db12ec10-f0db-49d6-a086-97b734d2c590.png)

**Desktop (please complete the following information):**
 - OS: windows 10 (k8s running on linux)
 - Web Browser: edge

**Additional context**

apologies if im completely misreading my results of course.

**Comment by mertyildiran** [comment]
@perezjasonr on `10.42.31.132` for example the name is not `kube-prometheus-stack-prometheus-node-exporter.monitoring` in reality, am I understanding it correctly?

> why is it picking those up? Im not tapping monitoring ns where they (node-exporter) are residing

Even though the pod that does the request is outside your tapped namespace, since the destination is inside the tapped namespace, the traffic is logged.

**Comment by mertyildiran** [comment]
@perezjasonr is it possible for you to create a minimal example that reproduces the issue using a few Kubernetes manifests?

**Comment by perezjasonr** [comment]
i might have something even more useful, i tore down the node-exporter daemonset, notice how the get requests continue! but now they are not attributed to node-exporter its just "unresolved", id be willing to bet this is because that node ip can no longer be associated with the node-exporter pod (because its gone), but the requests keep coming! this tells me it might be kubelet, or kube-proxy, or calico, etc...(im assuming kubelet).

I used a marker to show where the pods seem to have terminated mid tap stream:

![image](https://user-images.githubusercontent.com/42380628/153055385-3fb985af-38e1-4522-a800-74442322b04c.png)

**Comment by perezjasonr** [comment]
if you really want to reproduce exactly as me I would say just deploy kube-prometheus-stack (i used helm) or just the node-exporter component, and i would think user-agent kube health get requests to /healthz/ready and other health checks will be attributed to node-exporter.

even better, before deploying it, those health checks will likely already be there, just not attributed to node-exporter.
