### ISSUE TITLE
Spamming people to check out your Github?

### ISSUE THREAD

**Issue by AcidRaZor** [up9inc/mizu#786]
I'm not sure where you got my work address from (it's not published anywhere), but spamming people to check out your service/github is not the way to go to get interest in your product. I would suggest a couple of reddit posts/medium articles and being active on StackOverflows DevOps sections to get more interest in this project. 

I wouldn't have bothered with coming here, but your unsubscribe link doesn't work, so I assume it's just spamming people over and over with no regard to the laws set in most countries which goes against unsolicited emails.

**Comment by haiut** [comment]
@AcidRaZor many thanks for your feedback, it was definitely not our intention to spam anyone. My apologies for the broken unsubscribe link. Please contact me alex@up9.com and we'll take care of this ASAP.
