### ISSUE TITLE
Error parsing cluster URL

### ISSUE THREAD

**Issue by funwillis** [up9inc/mizu#794]
**Describe the bug**
Mizu not able to parse cluster URL.
`kubernetes port-forwarding error: error upgrading connection: error creating request: parse "https://rancher-test.net%2Fk8s%2Fclusters%2Fc-g59tp/api/v1/namespaces/mizu/pods/mizu-api-server/portforward": invalid URL escape "%2F"`

**To Reproduce**
1. Run `mizu tap my-custom-srv-deployment-7bdbb449f5-z54lr`

**Expected behavior**
Instance mizu UI displaying traffic.

**Logs**
[mizu_logs_2022_02_12__18_55_49.zip](https://github.com/up9inc/mizu/files/8054221/mizu_logs_2022_02_12__18_55_49.zip)

**Desktop (please complete the following information):**
 - OS: Linux 5.15.19-1-MANJARO SMP PREEMPT Tue Feb 1 16:58:17 UTC 2022 x86_64 GNU/Linux

**Comment by funwillis** [comment]
Hi @IgorGov , thank you for attending this request. 

I can share with you my k8s client config but name resolution and authentication takes place in a VPN closed environment that I'm not allowed to share.

You will notice that cluster name do not contain escaped characters but mizu will somehow add them while handling it
[common-test-config.txt](https://github.com/up9inc/mizu/files/8056437/common-test-config.txt)

Note: I had to add txt extension for GitHub to allow me uploading the file; original file do not contain extension.

**Comment by IgorGov** [comment]
Hi @funwillis,
Can you please check the [latest](https://github.com/up9inc/mizu/releases/tag/27.0-dev3) development build, and see if it helps resolving your issue. If not please attach the updated log file.

**Comment by funwillis** [comment]
Hi @IgorGov ,
mizu is able to parse rancher url now.

Thank you!

**Comment by IgorGov** [comment]
Glad to hear! closing the issue.
