### ISSUE TITLE
Spam email advertisement sent to my work mail

### ISSUE THREAD

**Issue by daliborfilus** [up9inc/mizu#823]
**Describe the bug**
The bug is that you bug people with unwanted emails.
Sending me advertisement to my PRIVATE, UNPUBLISHED WORK email address, *letting me know* that there is this new shiny thing I might want to use, is definitely NOT the way to get my attention!

How dare you? Who do you think you are, that you can send people emails without any consent?
How many people do you think this will annoy and piss off, instead of getting you the positive views you want?

I would have been interested, if you didn't do it like this! This totally ruins your reputation.

For the first thing, I want you to tell me **where** you got my work email address, because that third party who gave it to you is holding my personal information illegally. I didn't give anyone anywhere permission to use my, once again, private, unpublished, work email address.

Please, tell me your source of that information. 

And next time, don't spam people! There is enough spam and advertisements on the internet already.
Tech companies should be preventing and killing spam, not participate in this unethical practice!

And no, unsubscribe link doesn't justify your horrible action. Not now, not ever.

**To Reproduce**
Do nothing, don't publish your email address anywhere.

**Expected behavior**
No spam getting to my inbox.

**Comment by haiut** [comment]
@daliborfilus many thanks for your feedback, it was definitely not our intention to spam anyone. My apologies for the broken unsubscribe link. Please contact me at [alex@up9.com](mailto:alex@up9.com) and we'll take care of this ASAP.
