### ISSUE TITLE
Dont get traffic from my pods

### ISSUE THREAD

**Issue by Lamercho** [up9inc/mizu#996]
**Describe the bug**
My cluster have different name than cluster.local and I cant find in mizu docs a way to set the correct cluster name. This is the log from one of the tapper daemons:

```
[2022-04-13T06:41:33.986+0000] INFO  ▶ socket connection to ws://mizu-api-server.mizu.svc.cluster.local/wsTapper failed: dial tcp: i/o timeout, retrying 28 out of 30 in 2 seconds... ▶ [1 main.go:323 dialSocketWithRetry]
```

If the cluster name is not properly set than the generated url ws://mizu-api-server.mizu.svc.cluster.local/wsTappe is not valid and the connection cannot be made.

**Expected behavior**
There should e option to mizu like --cluster-name that sets the correct cluster name.

Please add --cluster-name or similar option to mizu. If there is another way to set this name please put it in the help docs.

**Comment by nimrod-up9** [comment]
@Lamercho , thanks for taking the time to submit the issue.

I think that we can simply remove the `.svc.cluster.local` suffix. k8s will be able to resolve by `<serviceName>.<namespace>`. We'll get to it in the next few days.

If you're up to it, you are welcome to make the change yourself. You can check of [wiki](https://github.com/up9inc/mizu/wiki) for project documentation, or you can reach out on [slack](https://join.slack.com/t/up9/shared_invite/zt-tfjnduli-QzlR8VV4Z1w3YnPIAJfhlQ) for any question we will be glad to support you.

**Comment by Lamercho** [comment]
Thank you, just submitted pull request.
